-- 쇼핑몰 프로젝트 테이블 정의
-- 테이블 종류
-- 1. 회원정보 테이블
-- 2. 상품 카테고리 테이블
-- 3. 상품 정보 테이블
-- 4. 상품 이미지 정보 테이블
-- 5. 장바구니 정보 테이블
-- 6. 구매 정보 테이블

-- 1. 회원정보 테이블

CREATE TABLE SHOP_MEMBER (
	MEM_ID VARCHAR(50) PRIMARY KEY
	, MEM_PW VARCHAR(100) NOT NULL
	, MEM_NAME VARCHAR(50) NOT NULL
	, MEM_TEL VARCHAR(30) UNIQUE
	, POST VARCHAR(10)
	, MEM_ADDR VARCHAR(50)
	, ADDR_DETAIL VARCHAR(100)
	, MEM_EMAIL VARCHAR(100)
	, MEM_ROLE VARCHAR(30) DEFAULT 'USER'
);

CREATE TABLE ITEM_CATEGORY(
	CATE_CODE INT AUTO_INCREMENT PRIMARY KEY
	, CATE_NAME VARCHAR(50) NOT NULL UNIQUE
);

-- ITEM_STATUS(상품상태) : 판매중(FOR_SALE), 매진(SOLD_OUT)
CREATE TABLE SHOT_ITEM(
	ITEM_CODE INT AUTO_INCREMENT PRIMARY KEY
	, ITEM_NAME VARCHAR(50) NOT NULL UNIQUE
	, ITEM_PRICE INT NOT NULL
	, ITEM_INTRO VARCHAR(100)
	, ITEM_STOCK INT DEFAULT 20
	, ITEM_STATUS VARCHAR(10) DEFAULT 'FOR_SALE'
	, CATE_CODE INT NOT NULL REFERENCES ITEM_CATEGORY (CATE_CODE)
);

SELECT * FROM shop_member;	

INSERT INTO SHOP_MEMBER (MEM_ID, MEM_PW, MEM_NAME, MEM_TEL, POST, MEM_ADDR, ADDR_DETAIL, MEM_EMAIL) 
VALUES ('TEST2', '1234', 'TEST2', '1234-5679', '12345', '울산', '북구땡땡동', 'abc123');



-- 아이디 중복 확인
SELECT MEM_ID 
FROM shop_member
WHERE MEM_ID = 'TEST2';
