CREATE TABLE CAR_INFO (
	MODEL_NUM INT AUTO_INCREMENT PRIMARY KEY 
	, MODEL_NAME VARCHAR(50) NOT NULL DEFAULT '아반떼' 
	, PRICE INT NOT NULL DEFAULT '0'
	, BRAND VARCHAR(50) NOT NULL DEFAULT '현대'
);

CREATE TABLE SALES_INFO (
	SALE_NUM INT AUTO_INCREMENT PRIMARY KEY
	, BUY_NAME VARCHAR(50) NOT NULL DEFAULT '구매자'
	, BUY_TEL VARCHAR(50) NOT NULL
	, COLOR VARCHAR(30) NOT NULL DEFAULT '블랙'
	, BUY_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, MODEL_NUM INT REFERENCES CAR_INFO (MODEL_NUM) ON DELETE CASCADE
);


SELECT * FROM car_info;
SELECT * FROM sales_info;

