-- 게시글 삭제할때 댓글도 같이 삭제되는 테이블


CREATE TABLE TEST_ITEM (
	ITEM_CODE INT AUTO_INCREMENT PRIMARY KEY
	, ITEM_NAME VARCHAR(30) NOT NULL
);

INSERT INTO TEST_ITEM VALUES (1, '상품1');
INSERT INTO TEST_ITEM VALUES (2, '상품2');
INSERT INTO TEST_ITEM VALUES (3, '상품3');

CREATE TABLE TEST_ORDER (
	ORDER_NUM INT AUTO_INCREMENT PRIMARY KEY
	, BUYER VARCHAR(50) NOT NULL
	, ITEM_CODE INT NOT NULL REFERENCES TEST_ITEM (ITEM_CODE) ON DELETE CASCADE
);

SELECT * FROM test_item;
SELECT * FROM TEST_ORDER;

DROP TABLE TEST_ITEM;
DROP TABLE TEST_ORDER;

INSERT INTO TEST_ORDER VALUES (1, '김자바', 1);
INSERT INTO TEST_ORDER VALUES (2, '김자바', 1);
INSERT INTO TEST_ORDER VALUES (3, '김자바', 2);
INSERT INTO TEST_ORDER VALUES (4, '김자바', NULL);





